import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul>
          <Link href="/"><li>Home</li></Link>
          <Link href="/Users"><li>Users</li></Link>
          <Link href="/Contact"><li>Contact</li></Link>
        </ul>
        {children}
      </body>
    </html>
  );
}
